#!/bin/bash

LAST_ONLINE_TIME_FILE="../records/last_online_time"

switch_dir() {
    script_folder=$(dirname "${BASH_SOURCE}")
    cd $script_folder
}

get_idle_time() {
    current_time_seconds=$(date "+%s")
    last_online_time_full=$(cat $LAST_ONLINE_TIME_FILE)
    last_online_time_seconds=$(date -d "$last_online_time_full" "+%s")
    interval_seconds=$(expr $current_time_seconds - $last_online_time_seconds)
    interval=$(expr $interval_seconds / 60)
    echo $interval
}

switch_dir
get_idle_time


