#!/bin/bash

LOG_FILE="../logs/no_player_online"

script_folder=$(dirname "${BASH_SOURCE}")
cd $script_folder

current_time=$(date)

validate_message(){
    message="$*"
    echo $message | grep "Turned off world auto-saving" && return 1
    echo $message | grep "Saving..." && return 1
    echo $message | grep "Saved the world" && return 1
    echo $message | grep "Turned on world auto-saving" && return 1
    echo $message | grep "Can't keep up!" && return 1
    echo $message | grep "UUID of player" && return 1

    return 0
}

_get_status_message(){
    echo "$(msm mod-server2 connected)"
}

get_status_message(){
    message=$(_get_status_message)
    until validate_message $message; do
        message=$(_get_status_message)
    done
    
    echo "$message"
}

message=$(get_status_message)
echo $message | grep 'No players are connected.' > /dev/null  && exit 0
echo $message | grep 'Server "mod-server2" is not running. No users are connected.' > /dev/null && exit 0

echo "$current_time: [ $message ] are connected." > $LOG_FILE
exit 1  # has player online


 
