#!/bin/bash

LOG_FILE="../logs/no_player_online"

script_folder=$(dirname "${BASH_SOURCE}")
cd $script_folder

current_time=$(date "+%c")

message=$(msm mod-server2 connected)
res=$(echo $message | grep 'No players are connected.')
if [[ -n "$res" ]]
then 
    exit 0  # no player online
else 
    echo "$current_time: [ $message ] are connected." > $LOG_FILE
    exit 1  # has player online
fi


 
