#!/bin/bash

SHUTDOWN_ENABLED_FILE="../records/shutdown_enabled"
ALLOWED_IDLE_TIME=60    # in minutes

switch_dir() {
    caller_path=$(pwd)
    script_folder=$(dirname "${BASH_SOURCE}")
    cd $script_folder
}


ensure_shutdown_enabled(){
    if [ ! -e "$SHUTDOWN_ENABLED_FILE" ]
    then
        exit 0
    fi
}

main() {    
    if ./no_player_online
    then
        idle_time=$(./get_idle_time)
        if [ "$idle_time" -ge "$ALLOWED_IDLE_TIME" ]
        then
            sudo shutdown -P +5 "no player active for $idle_time minutes. shutting down."
        fi
    fi
}

switch_dir
ensure_shutdown_enabled
main



